---
version: "3.9"

services:
  api:
    container_name: "${NGINX_API_HOSTNAME}"
    image: nginx:1.21.1-alpine
    ports:
      - "443:${NGINX_HTTPS_PORT}"
    environment:
      NGINX_API_HOSTNAME: "${NGINX_API_HOSTNAME}"
      NGINX_HTTPS_PORT: "${NGINX_HTTPS_PORT}"
      PRISM_MOCK_HOSTNAME: "${PRISM_MOCK_HOSTNAME}"
      PRISM_MOCK_PORT: "${PRISM_MOCK_PORT}"
      PRISM_PROXY_HOSTNAME: "${PRISM_PROXY_HOSTNAME}"
      PRISM_PROXY_PORT: "${PRISM_PROXY_PORT}"
    networks:
      - prism-mock
      - prism-proxy
    depends_on:
      - prism-mock
      - prism-proxy
    volumes:
      - "${PWD}/tools/docker/api/templates:/etc/nginx/templates:ro"
      - "${PWD}/tools/tls:/etc/tls:ro"
  prism-mock:
    container_name: "${PRISM_MOCK_HOSTNAME}"
    command: "mock -p ${PRISM_MOCK_PORT} -h 0.0.0.0 /tmp/${API_FILE}"
    image: stoplight/prism:4
    volumes:
      - "${PWD}/api.yml:/tmp/${API_FILE}:ro"
    expose:
      - "${PRISM_MOCK_PORT}"
    networks:
      - prism-mock
  prism-proxy:
    container_name: prism-proxy.shrikeh.local
    command: "proxy -p ${PRISM_PROXY_PORT} -h 0.0.0.0 /tmp/${API_FILE} ${API_ENDPOINT}"
    image: stoplight/prism:4
    volumes:
      - "${PWD}/api.yml:/tmp/${API_FILE}:ro"
    expose:
      - "${PRISM_PROXY_PORT}"
    networks:
      - prism-proxy

networks:
  prism-mock:
  prism-proxy:
