---
version: "3.9"

services:
  api:
    container_name: api.shrikeh.local
    image: nginx:1.21.1-alpine
    ports:
      - 443:443
    networks:
      - prism
    depends_on:
      - prism
    volumes:
      - "${PWD}/tools/docker/api/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "${PWD}/tools/tls:/etc/tls:ro"
  prism:
    container_name: prism.shrikeh.local
    command: "proxy -h 0.0.0.0 /tmp/${API_FILE} ${API_ENDPOINT}"
    image: stoplight/prism:4
    volumes:
      - "${PWD}/api.yml:/tmp/${API_FILE}:ro"
    expose:
      - 4010
    networks:
      - prism

networks:
  prism:
