---
version: "3.9"
services:
  api:
    container_name: "${NGINX_API_HOSTNAME:?err}"
    image: nginx:1.21.1-alpine
    ports:
      - "443:${NGINX_HTTPS_PORT:?err}"
    environment:
      NGINX_API_HOSTNAME: "${NGINX_API_HOSTNAME:?err}"
      NGINX_HTTPS_PORT: "${NGINX_HTTPS_PORT:-443}"
      PRISM_MOCK_PORT: "${PRISM_MOCK_PORT:?err}"
      PRISM_PROXY_PORT: "${PRISM_PROXY_PORT:?err}"
    depends_on:
      - prism-mock
      - prism-proxy
    volumes:
      - "${PWD}/tools/docker/api/templates:/etc/nginx/templates:ro"
      - "${PWD}/tools/tls:/etc/tls:ro"
  prism-mock:
    command: "mock -p ${PRISM_MOCK_PORT:?err} -h 0.0.0.0 /tmp/${API_FILE:?err}"
    image: "stoplight/prism:${STOPLIGHT_PRISM_TAG:-4.3.4}"
    volumes:
      - "${PWD}/api.yml:/tmp/${API_FILE:?err}:ro"
    expose:
      - "${PRISM_MOCK_PORT:?err}"
  prism-proxy:
    command: "proxy -p ${PRISM_PROXY_PORT:?err} -h 0.0.0.0 /tmp/${API_FILE:?err} http://pact-stub/"
    image: stoplight/prism:4
    volumes:
      - "${PWD}/api.yml:/tmp/${API_FILE:?err}:ro"
    expose:
      - "${PRISM_PROXY_PORT}"
    depends_on:
      - pact-stub
  pact-broker:
    image: pactfoundation/pact-broker:2.81.0.1
    environment:
      PACT_BROKER_DATABASE_HOST:                  "pact-broker-db"
      PACT_BROKER_DATABASE_NAME:                  "${PACT_BROKER_DB_NAME:?err}"
      PACT_BROKER_DATABASE_USERNAME:              "${PACT_BROKER_DB_USERNAME:?err}"
      PACT_BROKER_DATABASE_PASSWORD:              "${PACT_BROKER_DB_PASSWORD:?err}"
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES:   "5"
      PACT_BROKER_PORT:                           "${PACT_BROKER_PORT?:err}"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    depends_on:
      - pact-broker-db
    expose:
      - "${PACT_BROKER_PORT:?err}"
    ports:
      - "${PACT_BROKER_HOST_PORT:-?err}:${PACT_BROKER_PORT:?err}"
  pact-broker-db:
    image: postgres:13.4-alpine3.14
    restart: always
    healthcheck:
      test: "psql postgres --command 'select 1' -U ${PACT_BROKER_DB_USERNAME:?err}"
    volumes:
      - pact-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:       "${PACT_BROKER_DB_NAME:?err}"
      POSTGRES_USER:     "${PACT_BROKER_DB_USERNAME:?err}"
      POSTGRES_PASSWORD: "${PACT_BROKER_DB_PASSWORD:?err}"
  pact-stub:
    image: pactfoundation/pact-stub-server:v0.4.4
    command: "--dir /pacts -p 80"
    expose:
      - "80"
    ports:
      - "4141:80"
    volumes:
      - ./tests/pacts:/pacts:ro
  pact-cli:
    image: "pactfoundation/pact-cli:${PACT_CLI_TAG:-0.50.0.1}"
    environment:
      PACT_BROKER_BASE_URL: "http://pact-broker:${PACT_BROKER_PORT:?err}/"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    depends_on:
      - pact-broker

volumes:
  pact-postgres:
